### ISSUE TITLE
Promise and polyfill

### ISSUE THREAD

**Issue by oligot** [jadjoubran/promifill#1]
Hi,

We built a similar library at our company and one mistake we made was to use Promise at the API level.

This really depends on the browsers you want to support but some of them (hello IE 11) [don't support Promise](http://caniuse.com/#feat=promises).
We decided to replace the Promise API by a simple callback function as explained [in this great article](https://philipwalton.com/articles/loading-polyfills-only-when-needed/#loading-the-polyfills) and it now also works as expected in IE 11.

I'm not saying you should absolutely do the same here but if you don't, it would be a good idea to mention that your library depends on the Promise API so that people are aware that they have to load a Promise polyfill if they have to support IE11.

**Comment by jadjoubran** [comment]
Hi @oligot 
Thanks for making that point! Even though some users might not care about IE11, you're absolutely right. Especially that Android 4.4 does **not** support promises.

I will add a note in the Readme to use [promise-min](https://github.com/taylorhakes/promise-polyfill) for browsers that don't support promises

**Comment by oligot** [comment]
:raised_hands:
